---
# tasks file for guacamole

# docker_image requires the docker python module
- name: Install the docker python module
  pip:
    name:
      - docker[tls]

# docker pull guacamole/guacamole
- name: Pull guacamole docker image
  docker_image:
    name: guacamole/guacamole
    source: pull

# docker pull guacamole/guacd
- name: Pull guacd docker image
  docker_image:
    name: guacamole/guacd
    source: pull

# docker pull posgres for quacamole
- name: Pull postgres docker image for guacd
  docker_image:
    name: postgres
    source: pull

# Create the log directory
- name: Create the /var/log/docker directory
  file:
    path: /var/log/docker
    state: directory

# Copy the systemd unit file
- name: Copy the files for the guacamole docker build
  copy:
    src: "{{ item }}"
    dest: "/var/log/docker/{{ item }}"
    mode: 0644
  loop:
    - Dockerfile
    - init.sh
    - docker-compose.yaml

- name: Register initdb.sql
  stat:
    path: /var/log/docker/initdb.sql
  register: post_gres_init

- name: Get sql init script for postgres
  shell: |
    docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh \
    --postgres > /var/log/docker/initdb.sql
  when: not post_gres_init.stat.exists


# - name: Get sql init script for postgres
#   docker_image:
#     name: guacamole/guacamole
#     image: guacamole/guacamole
#     state: present
#     command: |
#       /opt/guacamole/bin/initdb.sh
#       --postgres > /var/log/docker/initdb.sql

# - name: build postgres image to be used by guacamole
#   shell: docker build --tag guac-postgres /var/log/docker/

- name: Build the postgres image for guacamole
  docker_image:
    name: postgres
    tag: guac-postgres
    build:
      path: /var/log/docker/
      pull: yes
    source: build
    state: present
