---
# tasks file for guacamole

# docker_image requires the docker python module
- name: Install the docker python module
  pip:
    name:
      - docker[tls]

# docker pull guacamole/guacamole
- name: Pull guacamole docker image
  docker_image:
    name: guacamole/guacamole
    source: pull

# docker pull guacamole/guacd
- name: Pull guacd docker image
  docker_image:
    name: guacamole/guacd
    source: pull

# docker pull postgres for guacamole
- name: Pull postgres docker image for guacd
  docker_image:
    name: postgres
    source: pull

# Create the directory for postgres docker
- name: Create a directory
  file:
    path: /var/postgres_docker
    state: directory

- name: Copy the files for the guacamole docker build
  copy:
    src: "{{ item }}"
    dest: "/var/postgres_docker/{{ item }}"
    mode: 0644
  loop:
    - Dockerfile
    - init.sh
    - docker-compose.yaml

- name: Register initdb.sql
  stat:
    path: /var/postgres_docker/initdb.sql
  register: postgres_initdb

- name: Create postgresql init script
  shell: >-
    docker run --rm guacamole/guacamole
    /opt/guacamole/bin/initdb.sh --postgres >
    /var/postgres_docker/initdb.sql
  when: not postgres_initdb.stat.exists

- name: Build the postgres image for guacamole
  docker_image:
    name: postgres
    tag: guac-postgres
    build:
      path: /var/postgres_docker
      pull: yes
    source: build
    state: present
