---
# tasks file for guacamole
- name: Create the /var/guacamole directory
  file:
    path: /var/guacamole
    state: directory
    mode: 0755

- name: Download and untar the guacamole-composition tarball
  unarchive:
    src: >
      https://api.github.com/repos/cisagov/guacamole-composition/tarball/develop
    dest: /var/guacamole
    remote_src: yes
    extra_opts:
      - "--strip-components=1"
    creates: /var/guacamole/docker-compose.yml

- name: Update dummy username/password with real values
  copy:
    content: "{{ item.contents }}"
    dest: "/var/guacamole/secrets/{{ item.filename }}"
  with_items:
    - {filename: "postgres-username", contents: "{{ postgres_username }}"}
    - {filename: "postgres-password", contents: "{{ postgres_password }}"}
  no_log: true
