---
# tasks file for guacamole
- name: Create the /var/guacamole directory
  file:
    path: /var/guacamole
    state: directory
    mode: 0755

- name: Download and untar the guacamole-composition tarball
  unarchive:
    src: >
      https://api.github.com/repos/cisagov/guacamole-composition/tarball/feature/kerberization
    dest: /var/guacamole
    remote_src: yes
    extra_opts:
      - "--strip-components=1"
    creates: /var/guacamole/docker-compose.yml

- name: Update dummy username/password with real values
  copy:
    content: "{{ item.contents }}"
    dest: "/var/guacamole/secrets/{{ item.filename }}"
    mode: 0664
  loop:
    - {filename: "postgres-username", contents: "{{ postgres_username }}"}
    - {filename: "postgres-password", contents: "{{ postgres_password }}"}
  no_log: true

- name: Configure Guacamole service
  block:
    - name: Set up Guacamole as a systemd service
      copy:
        src: guacamole-composition.service
        dest: /lib/systemd/system/
        mode: 0644

    - name: Systemd daemon-reload
      systemd:
        daemon_reload: true

    - name: Start Guacamole systemd service and enable it to start on boot
      systemd:
        name: guacamole-composition.service
        state: started
        enabled: true
  when:
    - ansible_service_mgr == "systemd"

- name: Configure httpd and PAM for guacamole
  block:
    - name: Copy guacamole PAM configuration
      copy:
        content: |
            auth    required   pam_sss.so
            account required   pam_sss.so
        dest: /etc/pam.d/guacamole
        mode: 0644

    - name: Copy guacamole httpd configuration
      copy:
        src: guacamole_httpd_config
        dest: /etc/apache2/sites-available/guacamole.conf
        mode: 0644

    - name: Enable guacamole httpd configuration
      file:
        src: /etc/apache2/sites-available/guacamole.conf
        dest: /etc/apache2/sites-enabled/guacamole.conf
        state: link
