---
# tasks file for guacamole
- name: Create the /var/guacamole directory
  file:
    path: /var/guacamole
    state: directory
    mode: 0755

- name: Download and untar the guacamole-composition tarball
  unarchive:
    src: >
      https://api.github.com/repos/cisagov/guacamole-composition/tarball/feature/kerberization
    dest: /var/guacamole
    remote_src: yes
    extra_opts:
      - "--strip-components=1"
    creates: /var/guacamole/docker-compose.yml

- name: Update dummy username/password with real values
  copy:
    content: "{{ item.contents }}"
    dest: "/var/guacamole/secrets/{{ item.filename }}"
    mode: 0664
  loop:
    - {filename: "postgres-username", contents: "{{ postgres_username }}"}
    - {filename: "postgres-password", contents: "{{ postgres_password }}"}
  no_log: true

- name: Configure guacamole service
  block:
    - name: Set up guacamole as a systemd service
      copy:
        src: guacamole-composition.service
        dest: /lib/systemd/system/
        mode: 0644

    - name: Systemd daemon-reload
      systemd:
        daemon_reload: true

    - name: Enable guacamole systemd service
      systemd:
        name: guacamole-composition.service
        enabled: true
  when:
    - ansible_service_mgr == "systemd"

- name: Configure PAM for guacamole and guacamole-admin services
  copy:
    content: |
        auth    required   pam_sss.so
        account required   pam_sss.so
    dest: /etc/pam.d/{{ item }}
    mode: 0644
  loop:
    - guacamole
    - guacamole-admin

  # * Disable port 80
  # * Create guacamole and guacamole-admin services
  # * Determine if we can get by with only the HTTP keytab in httpd
  # configuration or if we need the host keytab as well.
  # * Fix below tasks for non-Debian hosts
- name: Configure httpd for guacamole
  block:
    - name: Disable listening on port 80
      lineinfile:
        path: /etc/apache2/ports.conf
        state: absent
        regexp: Listen 80

    - name: Disable default httpd configuration
      file:
        path: /etc/apache2/sites-enabled/000-default.conf
        state: absent

    - name: Copy guacamole httpd configuration
      copy:
        src: guacamole_httpd_config
        dest: /etc/apache2/sites-available/guacamole.conf
        mode: 0644

    - name: Enable guacamole httpd configuration
      file:
        src: /etc/apache2/sites-available/guacamole.conf
        dest: /etc/apache2/sites-enabled/guacamole.conf
        state: link

- name: Copy setup script
  copy:
    src: setup_guacamole_services.sh
    dest: /usr/local/sbin
    mode: 0700
